westerndigitalcorporation/spdm-utils

README.md

Add a Table of Contents and center align the title.

README: add a table of contents

---

src/main.rs

This change allows the client to also initiate the tests suite. That is, first starting the responder as a server, then client with `tests`.

tests: allow socket_client to run tests

---

src/cli_helpers.rs
src/main.rs
src/responder.rs

This allows us to select the spdm data message version used by the libspdm responder. The default (as before) is version 1.3. We can now select versions 1.0..=1.3.
This is sub-argument to the response command, usage as below:
```
$ spdm_utils --qemu-server response --spdm-ver 1.3
```
Tested by running get-version request on a responder with version 1.0, 1.1, 1.2, 1.3. Note that, 1.0 fails on key-exchange, likely due to mismatched secure version. Will investigate.

spdm_version: add version select support

---

src/libspdm/spdm.rs

Log an error if the responder returns an unsupported capability. This allows us to still setup a session and try sending a request.
For instance, if the responder is using SPDM version 1.0, using keyexhcange is not supported in versions less than 1.1. We can log an error for such a case here as it isn't critical, but still send another request (get-version) later that isn't impaceted by this missing functionality.

request: minimal handling for responder unsupported capability

---

Cargo.lock
Cargo.toml
build.rs
src/doe_pci_cfg.rs
src/libspdm/spdm.rs
src/qemu_server.rs
src/socket_client.rs
src/socket_server.rs

These are some of the last steps to allow a basic no_std build

Cargo: More improvements for a no_std library build

---

Cargo.lock
Cargo.toml

Fixes: https://github.com/westerndigitalcorporation/spdm-utils/security/dependabot/1

Cargo: Bump dependencies

---

.gitmodules
tock-responder/Cargo.lock
tock-responder/Cargo.toml
tock-responder/Makefile
tock-responder/README.md
tock-responder/build.rs
tock-responder/src/libc_stubs.rs
tock-responder/src/main.rs
tock-responder/src/mctp.rs

@alistair23 I noticed on this branch the .tab size is ~100K higher than my original, I think because of the new dependencies added to the cargo.toml.

tock-responder:  add i2c transport and drop newlib/libtock-c dependencies

---

tock-responder/src/libc_stubs.rs

This adds support for `rand()` and `strncmp()`. With the implementation of `strncmp()` we can now issue `get-csr` to the device and view the certificate returned.
```shell
$ ./target/debug/spdm_utils --usb-i2c --usb-i2c-dev=/dev/ttyUSB0 --usb-i2c-baud=115200 request get-csr
...
$ openssl req -text -noout -inform der -verify -in ./csr_response.der
Certificate request self-signature verify OK
Certificate Request:
Data:
Version: 1 (0x0)
Subject: C = AU, O = Western Digital Test, CN = Western Digital AN300 Test CSR
Subject Public Key Info:
Public Key Algorithm: id-ecPublicKey
Public-Key: (384 bit)
pub:
04:47:90:2a:40:bd:9f:60:50:b7:18:13:b2:2b:02:
b7:fa:33:a1:2d:df:70:a9:e2:e5:72:92:9a:e6:ba:
f9:04:2c:de:06:90:27:91:71:47:11:9e:1d:91:cb:
74:21:67:23:a1:77:58:fc:2a:99:41:ed:7b:7b:b9: …
```

tock-responder: Implement more libc stubs

---

Cargo.lock
Cargo.toml
README.md
build.rs
src/cli_helpers.rs
src/libspdm/spdm.rs
src/main.rs
src/qemu_server.rs
src/usb_i2c.rs

Add transport layer support for using a uart-i2c bridge tool. Currently, designed to work with the libtock-rs usb-i2c sample app (not upstream yet).  The general idea is that, we wrap the SPDM data buffer with some metadata that includes the target destination and data length. This is then written to the bridge device over UART which then parses and write the SPDM message buffer to the target endpoint over I2C/SMBus. The endpoint will master the bus (as per MCTP), and write the response back to the bridge device, that then wraps the SPDM buffer in metadata before writing it back to host (spdm-utils).
This depends on **`libspdm chunking support`** (see README updates). We use chunking to send digestible buffers to the target. Without chunking we would need to be transferring buffers of …

spdm-utils: transport: usb-i2c support

---

src/libspdm/responder.rs
src/libspdm/spdm.rs
src/main.rs
src/usb_i2c.rs
tock-responder/README.md
tock-responder/src/libc_stubs.rs
tock-responder/src/mctp.rs

This bumps libspdm to the latest, and fixes some compliance issues on the responder. This commit of libspdm contains the changes required to get `set_cert` working on a `no_std` target (mbedtls time skip support).

spdm_utils: support latest libspdm

---

src/libspdm/responder.rs
src/libspdm/spdm.rs
src/main.rs

This implements the `libspdm_gen_csr_ex()` fn to allow us
to continue to support a `GET_CSR` in libspdm SPDM >= 1.3. This is limited
in the sense that we don't support CsrTrackingTags yet.
That is, a responder will immediately process the request and return the
CSR without needing a reset, as such, a requester must not request to
seek a CsrTrackingTag. Assertions are in place to catch such a case.

spdm: limited implementation of SPDM1.3 GET_CSR support

---

src/usb_i2c.rs
tock-responder/src/mctp.rs

This fixes the data on the wire to ensure we are sending correct MCTP packets.

Fixup the MCTP packets on the wire

---

.gitignore
Cargo.lock
Cargo.toml
README.md
build.rs
manifest/encode_cbor.py
src/libspdm/lib.rs
src/libspdm/manifest.rs
src/libspdm/spdm.rs

This adds support to spdm-utils to be able to cbor serialise a `manifest.in.cbor` file at compile time, then use the output binary file created as the `measurement manifest` to be used during a `get-measurements` index `0xFD` request.
The requester is also now able to decode this received manifest and print it out to the user in a human readable format.
Note: That the file `manifest.in.cbor` is left blank on purpose, such that a user can fill it out as required.

spdm: add manifest cbor enc/dec support

---

src/tcg_concise_evidence_binding.rs
src/test_suite.rs

Implement the remaining certificate checks to enforce the section "5.3 Certificate Contents" requirements.
There are still a few TODOs in the code. Mostly that we need to support multiple entries in the `id-spdm-cert-oids` `SEQUENCE` (section 414 of SPDM) and checking that the certificates are only used for what they are advertised for in seciont 5.3 of the TCG DICE Concise Evidence Binding for SPDM specification.
For single interactions via the command line we print the information for a human to review. We should look at integrating the results from `check_tcg_dice_evidence_binding()` into other requests in the test infrastructure to more accurately enforce requirements.

Implement remaining TCG Certificate Checks

---

src/libspdm/manifest.rs
src/libspdm/spdm.rs

Instead of panic-ing, let's return an error on cases where we are unable to decode the measurement manifest.
This is useful, if the target platform does not have access to the decode utilities (`cbor-diag`). Such targets can still use spdm-utils to extract the raw-bitstream of the measurement manifest received, and skip decoding all together.
Such a case should only occur when running in `requester` mode, for examle and embedded platform with limited access to required libraries.

manifest: handle decode failures

---

src/libspdm/lib.rs
src/libspdm/spdm.rs

This broke recently with some changes, fixup the build so the tock-responder can be built.

libspdm: Fix no_std build

---

src/libspdm/spdm.rs

Fixes: https://github.com/westerndigitalcorporation/spdm-utils/issues/63#issuecomment-2098389394

libspdm/spdm.rs: fixup missing import

---

Cargo.lock
Cargo.toml
src/libspdm/manifest.rs
src/libspdm/spdm.rs
tock-responder/Cargo.lock

This supports generating a direct manifest from an indirect manifest. This is based on the original discussion at [1].
1: https://gitlab.com/twittner/minicbor/-/merge_requests/39

libspdm: Support generating direct manifest

---

src/libspdm/spdm.rs

The measurement helper functions (like
libspdm_fill_measurement_image_hash_block()) already include the spdm_measurement_block_dmtf_t size and the length of the data in the return value. There is no need to calculate it twice.
This commit removes the second attempt to calculate total_size_needed. This fixes the wrong size being reported if changes are made to the measurement functions.

libspdm: spdm: Don't double count measurements

---

src/test_suite.rs

Cleanup the slot created by the requester after `set_certificate`. This fixes the issue where when testing over the socket mode, a subsequent test set will fail due to the additional slot(s) created by a prior test session.

test_suite: cleanup after testing set certificate

---

src/test_suite.rs

This builds on: https://github.com/westerndigitalcorporation/spdm-utils/pull/79 to cleanup the CSR artifacts also.

test_suite: cleanup after test CSR artifacts

---

src/cli_helpers.rs
src/main.rs

Allows the pcie vendor and device ids to be entered in either hex or base 10 format. This should maintain backwards compatibility also.

pcie_ids: allow hex argument inputs

---

src/cli_helpers.rs
src/doe_pci_cfg.rs
src/libspdm/spdm.rs
src/main.rs
src/qemu_server.rs
src/socket_server.rs
src/usb_i2c.rs

As we are moving towards a v1.0, let's try to not panic on trivial errors, instead log the error the propagate it up the call stack.
This does come at the cost of more verbose code, I _think_ that's justified when we need to debug, at least we can grep the error message instead of trying to figure out what failed.
Also add support to entering PCIe VID/DevIDs in hex format for the PCIe DOE transport layer. That is `0x` prefixed. We still accept base 10 as before as well.

Improve general error handling + PCIe Hex IDs

---

src/libspdm/spdm.rs

We were incorrectly passing the wrong address of `info` to `libspdm_hkdf_expand()`. We ended up passing a reference to info and casting it to the correct type.
Let's fix this up and just directly pass the pointer we were passed in the function arguments back to the libspdm `libspdm_hkdf_expand()` function.

libspdm: spdm: Fixup info buffer pointer for hkdf_expand

---

Cargo.lock
Cargo.toml
src/libspdm/spdm.rs
src/main.rs
tock-responder/Cargo.lock

Add a command line argument for responders to enable dynamic image measurement. This allows us to more accuratly model a real respnoder.
At startup we spawn two threads to hash the "kernel" and the application. We currently join them before running the responder, we actually only need to do this before generating the measurement, but there isn't a nice way to do that from the libspdm Rust library. I thought of a closure callback, but it's all a bit messy so the current approach will do for now.
`libspdm_fill_measurement_image_hash_block()` will now dynamically use a type of image block based on the init status of the `Lazy` `DYN_IMAGE_MEASURE`.

Add dynamic image measurement

---

src/request.rs
src/test_suite.rs

Instead of *just* extracting information from the session, ensure we issue the GET_VERSION/GET_CAPABILITIES requests.
Also support NEGOTIATE_ALGORITHMS  request.
Split from: https://github.com/westerndigitalcorporation/spdm-utils/pull/97

spdm-requests: make sure we alway issue requests

---

Cargo.lock
Cargo.toml
src/main.rs

Check that for DOE/USB_I2C, that `spdm-utils` was started with root privileges. Otherwise, print an error.

permissions: check effective user id at start

---

manifest/manifest.in.cbor

This patch converts the measurement OID to be BER encoded.
I used the following diff to generate the DER encoded data
```diff
diff --git a/src/main.rs b/src/main.rs
index 181ca0f..077ecc3 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -8,6 +8,8 @@
//! (which is generated from here) or the README
//!
+use asn1_rs::oid;
+use asn1_rs::ToDer;
use async_std::task;
use clap::{Parser, Subcommand};
use futures::future::join_all;
@@ -629,6 +631,10 @@ fn init_logger() {
#[async_std::main]
async fn main() -> Result<(), ()> {
init_logger();
+
+    let oid = oid!(1.3.6.1.4.1.5127);
+    panic!("OID: {:x?}", oid.to_der_vec());
+
let cli = Args::parse();
let cntx_ptr = spdm::initialise_spdm_context();
```
As [DER is a subset of BER](https://github.com/openssl/openssl/issues/7751#issuecomment-443950588) …

manifest: BER encode the OID

---

certs/alias/openssl.cnf
certs/setup_certs.sh

Split the requester and responder leaf certificate extensions so we can have a single SPDM Responder/Requester Authentication OID in each one.

certs: Split the requester and responder leaf cert extensions

---

README.md

This was tested by building `spdm-utils` on a fresh install of `linux-mint`.

README: add `apt` dependency support

---

build.rs

Instead of panicking at built time, just warn about the cbor tools not
being found. At run-time, `spdm-utils` will return an error when
attempting decode a cbor encoded manifest from a responder.
This should not affect a responder as we already have pre-generated
manifests checked in the `manifests/` directory.
The primary motivation for this is to allow the `Buildroot` package to be upstream friendly.

build.rs: warn if cbordiag tools are not found 

---

src/doe_pci_cfg.rs
src/io_buffers.rs
src/main.rs
src/qemu_server.rs
src/socket_client.rs
src/socket_server.rs
src/usb_i2c.rs

This allows us to remove alot of repeated code for buffer `set/get`. This approach uses a heap allocated vector and just passes a reference to `libspdm` when required.
The associated memory shall be explicitly freed
by taking ownership when the buffers are no longer required. Which can be done by calling `libspdm_drop_io_buffers()`.

spdm_transport: generic: refactor IO buffers

---

src/doe_pci_cfg.rs

During the discovery all tests, ensure we wait for the device to clear `STATUS::BUSY` before writing to the mailbox and setting DOR.

pci_doe: tests: add a status::busy check

---

src/cli_helpers.rs
src/doe_pci_cfg.rs
src/main.rs

If a device id and vendor id is not specified by user, scan the PCIe bus for devices that support DoE capability. Then suggest a list of options for the user to choose from. `spdm-utils` will read the specified device index from stdin then fetch the corresponding device and vendor ids.
Usage:
```
twilfred@fedora ~/spdm-utils (master) [SIGINT]> sudo ./target/debug/spdm_utils --doe-pci-cfg --no-session request get-version
[2025-01-09T03:44:38Z DEBUG spdm_utils] Logger initialisation [OK]
[2025-01-09T03:44:38Z DEBUG spdm_utils::doe_pci_cfg] Found device: 01:00.0 Non-Volatile memory controller [0108]: Western Digital Device [1b96:0001]
[2025-01-09T03:44:38Z INFO  spdm_utils::cli_helpers] Listing devices with PCIe DoE Support on this system
[2025-01-09T03:44:38Z INFO  spdm_utils::cli_helpers] …
```

doe_pci_cfg: add doe auto suggest support

---

src/io_buffers.rs
src/libspdm/spdm.rs

Some of the unit tests disable `CHUNK_CAP` support, in which case `DataTransferSize` must equal `MaxSPDMmsgSize`. 
To ensure the tests run correctly let's set `DataTransferSize` to `MaxSPDMmsgSize`

libspdm: spdm: Set DataTransferSize to MaxSPDMmsgSize

---

build.rs

Pass the STAGING_INCDIR information to bindgen. This allows OE/Yocto to build SPDM-Utils.

build.rs: Supply STAGING_INCDIR to bindgen

---

Cargo.lock
Cargo.toml
src/cli_helpers.rs
src/doe_pci_cfg.rs
src/io_buffers.rs
src/libspdm/spdm.rs
src/main.rs
src/qemu_server.rs
src/socket_client.rs
src/socket_server.rs
src/usb_i2c.rs

With rust2024 [1],  "The [static_mut_refs](https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#static-mut-refs) lint level is now deny by default. This checks for taking a shared or mutable reference to a static mut."
This patch set aims to fix all these warning by replacing `static muts` with types that provide interior mutability and thread safety.
[1] https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html

rust24: fixup static_mut_refs warning and improve generaly safety

---

src/doe_pci_cfg.rs
src/io_buffers.rs
src/libspdm/spdm.rs
src/main.rs
src/qemu_server.rs
src/request.rs
src/socket_client.rs
src/socket_server.rs
src/test_suite.rs
src/usb_i2c.rs

This preapres for the update to the Rust 2024 edition.
After this PR is merged we can at least build (with warnings) Rust 2024.
Rust 2024 needs Rust 1.85, which we don't really want just yet, but let's
at least get ready.
This is a fairly mechanical change, mostly just wrapping unsafe function
calls with unsafe instead of relying on the calling function being
unsafe.
This brings the number of unsafe keywords in our code base significantly
higher, which is a shame. Overall the actual unsafe code is the same,
just more accurately described.
Hopefully this can be improved in the future, especially if we can remove
some of the C style pointer operations.

Prepare for Rust 2024 edition

---

src/test_suite.rs

fixes: https://github.com/westerndigitalcorporation/spdm-utils/issues/143

test_suite: add missing `unsafe` wrap
